/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
    theme: {
        extend: {},
    },
    daisyui: {
        // themes: ["light", "dark", "cupcake", "bumblebee", "emerald", "corporate", "synthwave", "retro", "cyberpunk", "valentine", "halloween", "garden", "forest", "aqua", "lofi", "pastel", "fantasy", "wireframe", "black", "luxury", "dracula", "cmyk", "autumn", "business", "acid", "lemonade", "night", "coffee", "winter"],
        themes: [
            {
                bloomberg: {
                    "primary": "#FFA100",
                    "secondary": "#429016",
                    "accent": "#850211",
                    "neutral": "#424242",
                    "base-100": "#424242FF",
                    "base-200": "#0D0A13",
                    "base-300": "#000000",
                    "info": "#3BBAFF",
                    "success": "#5BCB67",
                    "warning": "#FFFE45",
                    "error": "#FA3524",
                },
            },
            "light",
            "dark",
            "bumblebee",
            "corporate",
            "synthwave",
            "retro",
            "cyberpunk",
            "valentine",
            "halloween",
            "garden",
            "forest",
            "aqua",
            "lofi",
            "pastel",
            "fantasy",
            "wireframe",
            "black",
            "luxury",
            "dracula",
            "cmyk",
            "autumn",
            "business",
            "acid",
            "lemonade",
            "night",
            "coffee",
            "winter"
        ],
    },
    plugins: [require("daisyui")],
};
